### PR TITLE
feature/B5SOM

### PR DESCRIPTION
**Pull request by busticated**
https://app.clubhouse.io/particle/story/42780/update-binary-version-reader-to-support-b5som-platform

### CODE REVIEW

**Comment by busticated** [comment]
@suda any hints on how to get CI doing the right thing on this one?

**Comment by busticated** [comment]
@avtolstoy consider this a teaching moment - i'm pretty fuzzy on how all of this works. it looks to me like:

1. nothing uses the `ModuleInfoPlatform` data [here](https://github.com/particle-iot/binary-version-reader/pull/27/files#diff-d3274290322679178de8b7c6f8bfef2aR79)
2. the [change](https://github.com/particle-iot/binary-version-reader/commit/2ff1e0b77f76a3412f76298385fc438bc782a86a) made in `v0.6.4` covers the B5 SoM as well

what else needs to be updated such that `particle binary inspect` returns accurate info and the cloud has the correct bits?

**Comment by avtolstoy** [comment]
@busticated 

1. Correct. Most of the tools/services utilizing `binary-version-reader` have hardcoded platform-ids and other things. The 'enums' in `ModuleInfo` are an attempt to clean that up for new code.
2 :+1:

For `particle binary inspect` most likely just https://github.com/particle-iot/particle-cli/blob/master/src/lib/utilities.js#L332

For device-service and SMH at the very least I don't think we need to do anything.

**Comment by suda** [comment]
@busticated I updated the pipeline and it passes now: https://g.codefresh.io/build/5df2668f83e4d146cd2d2dcb?viewName=

**Comment by busticated** [comment]
@suda thanks 🙏 - i tried re-running the integration here but it failed again. not sure what's up. merging anyway :+1:

**Comment by suda** [comment]
I think restarting used the old YAML. Your merge went through tho: https://g.codefresh.io/build/5df2709fb2d82b56b86e2a65?viewName=

**Pull request merged**
